### ISSUE TITLE
Publish to Melpa

### ISSUE THREAD

**Issue by jacksonrayhamilton** [dotmilk/emacs-crystal-mode#11]
It looks like [over here](https://github.com/jpellerin/emacs-crystal-mode/issues/14), a few users of this package named your repository as a new collective upstream for crystal-mode.

Earlier, [someone suggested publishing crystal-mode to Melpa](https://github.com/jpellerin/emacs-crystal-mode/issues/6), but the original author didn't feel the package was ready.

Do you feel differently and want to try to publish it?

I'd say it doesn't make a difference if the package is "incomplete." Publishing the package to Melpa just makes it easier to install.

**Comment by jacksonrayhamilton** [comment]
Also, if you did publish to Melpa, you might also want to consider publishing "flycheck-crystal" as a separate package. #12 would help with that.

**Comment by dotmilk** [comment]
I've never published a package to melpa. I will try and do so later tonight.

**Comment by nylar** [comment]
Any progress on this?

**Comment by dotmilk** [comment]
Sorry, I have not gotten around to fixing the checkdoc problems, if either of you @jacksonrayhamilton  or @nylar want to fix up the checkdoc docstrings errors and submit a pull request i will go ahead and attempt to publish on melpa

**Comment by jacksonrayhamilton** [comment]
It looks like this is now being maintained at https://github.com/crystal-lang-tools/emacs-crystal-mode and it is published to Melpa.

As a side note, maybe a notice should be added to this repo about its new home?

**Comment by RX14** [comment]
Looks like the `crystal-lang-tools` repository doesn't have some of the commits from this fork. @faustinoaq?

**Comment by faustinoaq** [comment]
@RX14 Yeah, I think I used the @ggiraldez fork. Let me pull this repo too 👍

**Comment by faustinoaq** [comment]
Done! 🎉
