### ISSUE TITLE
method with nullable return value

### ISSUE THREAD

**Issue by tbrand** [dotmilk/emacs-crystal-mode#20]
Correct
```crystal
def test : Array(String)?
  ["abc"]
end
```

Wrong (Current)
```crystal
def test : Array(String)?
             ["abc"]
end
```

**Comment by brantou** [comment]
@tbrand I recently improved crystal-mode indentation, probably solved the problem you encountered. Welcome to try. #https://github.com/crystal-lang-tools/emacs-crystal-mode/pull/15

**Comment by tbrand** [comment]
Awesome!:tada: Will try it!
